---
title: "Next Word Prediction: About Page"
author: "Diane Wenke"
date: "May 6, 2018"
output: html_document
---

This application was developed for the **Coursera Data Science Capstone Final Project**. 
The goal of the project is to create a product to highight a next word prediction algorithm 
and to provide a user interface to that can be accessed by others to utilze the algorithm.

### Application Open / User Interface
1. When the application is initially opened, the User Entry box will be blank and the Next Word Prediction box will display **"NULL"** 
2. The user then enters part of a sentence in the User Interface section, the next word prediction logic will be activated

### Actions / Results
1. After the user starts to enter a sentence, the next word the application's algorithm predicted will be displayed in the Next Word Prediction textbox
2. The user's entry will be displayed in the Next Word Prediction section
3. In addition, the type of n-gram algorithm (e.g. 3-gram) used in the prediction is displayed

#### Documentation:
1. Presentation slide deck: Available on the [RPubs page](http://rpubs.com/DWenke1/capstone)
2. Source code for ui.R and server.R files: Available on the [GitHub repo](https://github.com/DWenke/Data-Science-Capstone-Final-Project)
3. About, ReadMe, PNG and JPG files: Available on the [GitHub repo](https://github.com/DWenke/Data-Science-Capstone-Final-Project)
4. Cleansed data: Available on the [GitHub repo](https://github.com/DWenke/Data-Science-Capstone-Final-Project)

